### PR TITLE
IOS Version

### PR DESCRIPTION
**Pull request by maddijoyce**
Hi, not sure if you're interested in this, but I added an ios version to this library.
It just pulls the info.plist file from ios as a dictionary.

Cheers,
Maddi

### CODE REVIEW

**Comment by ismaeldcom** [comment]
Hi Maddi, I just push a new commit to unify JS style mainly.

I really appreciate your contribution, I didn't have time lately to spend in RN projects and had the iOS version eternally posponed.

I make you contributor to place on record your authorship and I'll add to collaborators in case you need to update the iOS part in the future.

Thanks
Cheers ;)

**Comment by maddijoyce** [comment]
Thanks Ismael, glad I could help!

**Comment by maddijoyce** [comment]
@ismaeldcom sorry to bother again. Is it possible to release the new version on npm?

**Comment by ismaeldcom** [comment]
Of course, I just forget to update, thanks for request it.

**Pull request merged**
